### ISSUE TITLE
Noob can't load Solution

### ISSUE THREAD

**Issue by derek-baker** [mmusket/vue-mvc#1]
Neither project will load in Visual Studio 2017 Community when I select the .sln file in this repo.

Is there something I'm missing?

**Comment by mmusket** [comment]
Hmm what does output window say? 
The projects are configured to use IIS so you would need to open visual studio  with admin rights. 
I had written these in vs 2015 but it should open without issues in newer versions.

**Comment by derek-baker** [comment]
Well. I feel foolish now. 

Issue was indeed that I needed to run VS as admin.

Thanks.

**Comment by mmusket** [comment]
no problem :)
